name: my_flutter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  flutter_tts: ^3.5.2
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Specify your assets here
  assets:
    - assets/images/
    - assets/icons/
